name = "ClosedHeaven"
uuid = "157dcac7-0992-462f-9d14-6f615505fb75"
version = "0.1.0"
authors = ["Mikhail <mkhrenov34@gmail.com>"]

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.9.15"
